config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'customers/show'

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }
  devise_scope :customer do
    get 'residences', to: 'customers/registrations#new_residence'
    post 'residences', to: 'customers/registrations#create_residence'
  end

  devise_for :shopkeepers, controllers: {
    registrations: 'shopkeepers/registrations',
    sessions: 'shopkeepers/sessions',
    passwords: 'shopkeepers/passwords'
  }
  devise_scope :shopkeeper do
    get 'addresses', to: 'shopkeepers/registrations#new_address'
    post 'addresses', to: 'shopkeepers/registrations#create_address'
  end

  resources :shops, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :items, only: [:show, :new, :create, :edit, :update ,:destroy] do
      collection do
        get 'search'
      end
      resources :itemcomments, only: :create
      resources :purchases, only: [:index, :create] do
        collection do
          get 'done'
        end
      end
    end
    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resources :tweetcomments, only: :create
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :customers, only: :show
  resources :residences, only: [:show, :update]
  resources :shopkeepers, only: :show
  resources :address, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :favorites, only: :index

  root to: "shops#index"

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :shopkeeper
  has_many :items, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :customers, through: :favorites
  has_one_attached :image
  belongs_to :itemcategory

  validates :name, :text, :image, :itemcategory, presence: true
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :shop_set, only: [:show, :edit, :update, :destroy]
  before_action :search_shop, only: [:index, :search]
  before_action :search_item, only: :show

  def index
    @shops = Shop.all
  end

  def show
    @items = @shop.items
    if customer_signed_in?
      @favorite = current_customer.favorites.find_by(shop_id: params[:id])
    end
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end 

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render "edit"
    end
  end

  def destroy
    if @shop.destroy
      redirect_to root_path
    else
      render "edit"
    end
  end

  def search
    @result_shops = @a.result.includes(:itemcategory)
  end
  
  private

  def shop_params
    params.require(:shop).permit(:name, :text, :itemcategory_id, :image).merge(shopkeeper_id: current_shopkeeper.id)
  end

  def shop_set
    @shop = Shop.find(params[:id])
  end

  def search_shop
    @a = Shop.ransack(params[:q])
    @itemcategory_parent_id = Itemcategory.where(ancestry: nil)
  end

  def search_item
    shop = Shop.find(params[:id])
    @p = shop.items.ransack(params[:q])
    @shipday = Shipday.where.not(id: 1)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<%= render 'shared/header' %>

<div class="shop-new">
  <div class="shop-new-shop">
    <%= form_with model: @shop, local:true do |f| %>
      <%= render 'shared/error_messages', model: @shop %>
      <div class="shop-field">
        店名
      </div>
        <%= f.text_field :name, class:"shop-field-input", placeholder:"例）新鮮で美味しさ満点！！野菜農園（必須 40文字まで）", maxlength:"40" %>
      <div class="shop-field">
        商品の画像（お店のトップ画像となります）
        <div class="shop-new-shop-images">
          <%= f.label :image, for:"item-new-image", class:"shop-label" do %>
            画像を選択してください
            <%= f.file_field :image, class:"shop-image-select", id:"item-new-image", style: "display: none;" %>
          <% end %>
        </div>
      </div>
        <div class="item-new-item-images", id="items-new-image">
        </div>

    <div class="shop-field">
      店の種類（お店の検索に使用します）
    </div>
    <%= f.collection_select(:itemcategory_id, Itemcategory.where(ancestry: nil), :id, :name, {include_blank:"選択してください"}, {class:"shop-field-select"}) %>
    <div class="shop-field">
      店舗の説明
    </div>
    <%= f.text_area :text, class:"shop-field-area-input", placeholder:"例）野菜の瑞々しさ、本来の自然な甘さ、食べたことはありますか？野菜農園は、標高の高い土地で野菜を作るので野菜本来の旨味を贅沢に味わえます。ツイートではそんな新鮮野菜を使ったレシピなどもご紹介します。新鮮野菜を摂り健康な体を作りましょう。（必須 1,000文字まで）", maxlength:"1000" %>
    <div class="edit-actions">
      <%= f.submit "編集を完了する", class:"action-link" %>
      <%= link_to "店を削除する", shop_path, method: :delete, class:"action-link"%>
    </div>
    <% end %>
  </div>
  <div class="shop-new-imformation">
    <b><a href="#">利用規約</a>
  </div>
</div>

app/views/shops/index.html.erb
<%= render 'shared/header' %>

  
<div class="top">
  <div class="main-left">
    <div class="search-shops">
      <h4>お店を探す</h4>
      <ul class="shop-search">
        <% @itemcategory_parent_id.each do |parent| %>
          <%= link_to search_shops_path(@a, :'q[itemcategory_id_eq' => "#{parent.id}"), class:"parent-category" do %>
            <li><%= parent.name %></li>
          <% end %>
        <% end %>
        <% if customer_signed_in? %>
          <%= link_to favorites_path, class:"parent-category" do %>
            <li>お気に入り</li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="main-right">
  <div class="top-sale">
    <div class="sale-image">
    <%= link_to "#" do %>
      <%= image_tag '/welcome.png',class:"main-image" %>
    <% end %>
    </div>
  </div>
    <ul class="main-shops">
      <% @shops.each do |shop| %>
        <li class="main-shops-list">
          <%= link_to shop_path(shop.id), class:"main-shops-link" do %>
            <div class="main-shop-name">
              <%= shop.name %>
            </div>
            <%= image_tag shop.image, class: "main-shop-image" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shops/new.html.erb
<%= render 'shared/header' %>

<div class="shop-new">
  <div class="shop-new-shop">
    <%= form_with model: @shop, local:true do |f| %>
      <%= render 'shared/error_messages', model: @shop %>
      <div class="shop-field">
        店名
      </div>
      <%= f.text_field :name, class:"shop-field-input", placeholder:"例）新鮮で美味しさ満点！！野菜農園（必須 40文字まで）", maxlength:"40" %>
      <div class="shop-field">
        商品の画像（お店のトップ画像となります）
        <div class="shop-new-shop-images">
          <%= f.label :image, for:"item-new-image", class:"shop-label" do %>
            画像を選択してください
            <%= f.file_field :image, class:"shop-image-select", id:"item-new-image", style: "display: none;" %>
          <% end %>
        </div>
      </div>
      <div class="item-new-item-images", id="items-new-image">
      </div>
      <div class="shop-field">
        店の種類（お店の検索に使用します）
      </div>
      <%= f.collection_select(:itemcategory_id, Itemcategory.where(ancestry: nil), :id, :name, {include_blank:"選択してください"}, {class:"shop-field-select"}) %>
      <div class="shop-field">
        店舗の説明
      </div>
      <%= f.text_area :text, class:"shop-field-area-input", placeholder:"例）野菜の瑞々しさ、本来の自然な甘さ、食べたことはありますか？野菜農園は、標高の高い土地で野菜を作るので野菜本来の旨味を贅沢に味わえます。ツイートではそんな新鮮野菜を使ったレシピなどもご紹介します。新鮮野菜を摂り健康な体を作りましょう。（必須 1,000文字まで）", maxlength:"1000" %>
      <div class="actions">
        <%= f.submit "出店する",class:"action-link" %>
      </div>
    <% end %>
  </div>
  <div class="shop-new-imformation">
    <b><a href="#">利用規約</a>
  </div>
</div>

app/views/shops/search.html.erb
<%= render 'shared/header' %>


<div class="top">

  <div class="main-left">
    <div class="search-shops">
      <h4>お店を探す</h4>
      <ul class="shop-search">
        <% @itemcategory_parent_id.each do |parent| %>
          <%= link_to search_shops_path(@a, :'q[itemcategory_id_eq' => "#{parent.id}"), class:"parent-category" do %>
            <li><%= parent.name %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="main-right">
    <% if @result_shops.present? %>
    <ul class="main-shops">
      <% @result_shops.each do |shop| %>
        <li class="main-shops-list">
          <%= link_to shop_path(shop.id), class:"main-shops-link" do %>
            <div class="main-shop-name">
              <%= shop.name %>
            </div>
            <%= image_tag shop.image, class: "main-shop-image" %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <% else %>
      お探しのお店は見つかりませんでした
      <%= link_to "トップへ戻る", root_path, class:"action-link" %>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<%= render 'shared/header' %>

<div class="shops-show-main">
  <div class="shops-show-left">
    <div class="search-items">
      <h4>このお店の商品を探す</h4>
      <ul class="item-search">
        <%= search_form_for @p, url:search_shop_items_path(@shop.id) do |f| %>
          <li>カテゴリー
            <%= f.collection_select(:itemcategory_id_eq, Itemcategory.find(@shop.itemcategory_id).children, :id, :name, {include_blank:"指定なし"}, {class:"search-items-select"}) %></li>
          <li>発送までの日数
            <%= f.collection_select(:shipday_id_eq, @shipday, :id, :name, {include_blank:"指定なし"}, {class:"search-items-select"}) %></li>
          <li>価格<br>
            <%= f.radio_button :price_lteq, "" %>
              指定なし<br>
            <%= f.radio_button :price_lteq, "1000" %>
              1,000円以下<br>
            <%= f.radio_button :price_lteq, "2500" %>
              2,500円以下<br>
            <%= f.radio_button :price_lteq, "5000" %>
              5,000円以下
          </li>

          <div class="search-action">
            <%= link_to "クリア", shop_path(@shop), class:"search-link" %>
            <%= f.submit "完了", class:"search-link"%>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="shops-show-right">
    <div class="shops-show-shop">
      
      <div class="shop-name">
        <%= link_to  @shop.name, shop_path(@shop.id), class:"item-show-shop-link" %>
          <% if customer_signed_in? %>
            <% if @favorite.present? %>
              <%= link_to shop_favorite_path(@shop), method: :delete, class:"favorite-delete" do %>
                <i class="fas fa-heart"></i>お気に入り中
              <% end %>
            <% else %>
              <%= link_to shop_favorites_path(@shop), method: :post, class:"favorite-new" do %>
                <i class="far fa-heart"></i>お気に入り登録
              <% end %>
            <% end %>
          <% end %>
      </div>
      <div class="shops-show-shop-top">
        <div class="shops-show-shopkeeper-link">
          <% if shopkeeper_signed_in? && current_shopkeeper.id == @shop.shopkeeper_id %>
            <p class="shop-btn">
              <%= link_to "出品", new_shop_item_path(@shop.id), class:"action-link" %>
            </p>
            <p class="shop-btn">
              <%= link_to "店舗の編集・削除", edit_shop_path(@shop.id), class:"action-link"%>
            </p>
          <% end %>
          <p class="shop-btn">
            <%= link_to "投稿", shop_tweets_path(@shop.id), class:"action-link" %>
          </p>
        </div>
      </div>
      <div class="shops-show-shop-image">
        <%= image_tag @shop.image, class:"shops-show-image" %>
      </div>
      <div class="shops-show-shop-text">
        <%= simple_format(@shop.text) %>
      </div>
      <% if shopkeeper_signed_in? && current_shopkeeper.id == @shop.shopkeeper_id %>

      <% end %>
    </div>
    
    <div class="items">
      <div class="shops-show-items-show-title">
        商品一覧
      </div>
      <ul class="shops-show-items-show">
        <% @items.each do |item| %>
          <li class="shops-show-items-list">
            <%= link_to shop_item_path(@shop.id, item.id), class:"shops-show-item-link" do %>
              <div class="shops-show-items-image">                
                <%= image_tag item.image, class: "shops-show-item-image" %>
              </div>
              <div class="shops-show-items-detail">
                <div class="shops-show-items-name">
                  <%= item.name %>
                </div>
                <div class="shops-show-items_price">
                  ￥<%= item.price %>
                </div>
                <% if item.stock == 0 %>
                  <div class="sold-out">
                    <b>完売</b>
                  </div>
                <% end %>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
    