config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'customers/show'

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }
  devise_scope :customer do
    get 'residences', to: 'customers/registrations#new_residence'
    post 'residences', to: 'customers/registrations#create_residence'
  end

  devise_for :shopkeepers, controllers: {
    registrations: 'shopkeepers/registrations',
    sessions: 'shopkeepers/sessions',
    passwords: 'shopkeepers/passwords'
  }
  devise_scope :shopkeeper do
    get 'addresses', to: 'shopkeepers/registrations#new_address'
    post 'addresses', to: 'shopkeepers/registrations#create_address'
  end

  resources :shops, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :items, only: [:show, :new, :create, :edit, :update ,:destroy] do
      collection do
        get 'search'
      end
      resources :itemcomments, only: :create
      resources :purchases, only: [:index, :create] do
        collection do
          get 'done'
        end
      end
    end
    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resources :tweetcomments, only: :create
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :customers, only: :show
  resources :residences, only: [:show, :update]
  resources :shopkeepers, only: :show
  resources :address, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :favorites, only: :index

  root to: "shops#index"

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :shopkeeper
  belongs_to :shop
  has_many :tweetcomments
  has_one_attached :image

  validates :title, :text, presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :destroy]
  before_action :set_shop

  def index
    @tweets = @shop.tweets.order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = @shop.tweets.new(tweet_params)
    if @tweet.save
      redirect_to shop_tweets_path(@shop)
    else
      render "new"
    end
  end

  def show
    @tweetcomment = Tweetcomment.new
    @tweetcomments = @tweet.tweetcomments.last(10)
  end

  def destroy
    if @tweet.destroy
      redirect_to shop_tweets_path(@tweet.shop.id)
    else
      render :index
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :text, :image).merge(shopkeeper_id: current_shopkeeper.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.erb
<%= render 'shared/header' %>

<div class="tweet-index">
  <div class="tweet-shop">
    <div class="tweet-shop-image">
      <%= link_to shop_path(@shop) do %>
        <%= image_tag @shop.image, class:"tweet-index-shop-image"%>
      <% end %>
    </div>
    <div class="tweet-shop-title">
      <div class="tweet-shop-top">
        <div class="tweet-shop-name">
          <%= link_to shop_path(@shop) do %>
            <h3><%= @shop.name %></h3>
          <% end %>
        </div>
        <div class="tweet-shop-tweet">
          <% if shopkeeper_signed_in? && current_shopkeeper.id == @shop.shopkeeper_id %>
            <%= link_to "投稿する", new_shop_tweet_path(@shop.id), class:"tweets-new-link" %>
          <% else %>
            
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="tweet-center">
  </div>
  <div class="tweets">
    <div class="tweet-images">
      <ul class="shop-tweets">
        <% @tweets.each do |tweet| %>
        <li class=" tweet-list">
          <%= link_to shop_tweet_path(@shop.id, tweet.id) do %>
            <%= image_tag tweet.image, class:"tweet-image" %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'shared/header' %>

<div class="tweet-new-top">
  <div class="tweet-new-tweet">
    <%= form_with model: [@shop, @tweet], class:"tweet-new-input", local: true do |f| %>
      <div class="tweet-new-images">
        <%= f.label :image, for:"item-new-image", class:"tweet-new-image-label" do %>
          画像選択
          <%= f.file_field :image, class:"tweet-new-image-select", id:"item-new-image", style:"display: none;" %>
        <% end %>
      </div>
      <div class="item-new-item-images", id="items-new-image">
      </div>
      <div class="tweet-new-title">
        タイトル
      </div>
        <%= f.text_field :title, class:"tweet-new-title-input", placeholder:"例）かぼちゃの煮物 のレシピをご紹介！ （必須 30文字まで）" %>
      <div class="tweet-new-text">
        内容
      </div>
        <%= f.text_area :text, class:"tweet-new-text-input", placeholder:"例） 材料：かぼちゃ、水、①醤油、①砂糖、①みりん
        １.かぼちゃのタネを取り除きます 
        ２.かぼちゃにぴったりとラップしレンジで加熱したら、カットします 
        ３.鍋に水とかぼちゃと①全てを入れて落とし蓋をして中火にかけます
        ４.ふつふつして来たら弱火にしてかぼちゃが柔らかくなるまで煮れば完成！" %>
      <div class="tweet-complete">
        <%= f.submit "投稿", class:"tweet-new-listing" %>
      </div>
    <% end %>
  </div>
  <div class="tweet-imfomation">
    注意点
  </div>
</div>

app/views/tweets/show.html.erb
<%= render 'shared/header' %>

<div class="tweet-show">

  <div class="tweet-show-top">
    <div class="tweet-show-image">
      <%= image_tag @tweet.image.variant(resize: '400x300') if @tweet.image.present? %>
    </div>
    <div class="tweet-show-createdtime">
      <%= l @tweet.created_at %>
    </div>
  </div>
  <div class="tweet-show-title">
    <h3><%= @tweet.title %></h3>
    </div>
  <div class="tweet-show-text">
    <%= simple_format(@tweet.text) %>
  </div>
  <div class="tweet-delete">
    <% if shopkeeper_signed_in? && current_shopkeeper.id == @tweet.shopkeeper_id %>
      <%= link_to "削除", shop_tweet_path(@tweet), method: :delete, class:"action-link" %>
    <% end %>
  </div>

  <div class="tweet-comments">
    <div class="tweet-comment-new">
      <% if shopkeeper_signed_in? || customer_signed_in? %>
        <%= form_with(model: [@shop, @tweet, @tweetcomment], class:"tweet-comment", local:true) do |f| %>
          <%= f.text_area :text, class:"tweet-comment-input", placeholder:"コメント" %>
          <%= f.submit "送信", class:"tweet-comment-send"%>
        <% end %>
      <% end %>
    </div>
    <div class="tweet-comments-all" id="comments">
      <% if @tweetcomments.present? %>
        <% @tweetcomments.reverse_each do |tweetcomment| %>
          <div class="tweet-comment-list">
            <div class="tweet-comment-top">
            <div class="tweet-comment-name">
              <% if tweetcomment.shopkeeper_id.present? %>
                <%= tweetcomment.tweet.shop.name %>
              <% elsif tweetcomment.customer_id.present? %>
                <%= tweetcomment.customer.nickname %>
              <% end %>
            </div>
            <div class="tweet-comment-time">
            <% tweetcomment.created_at %>
            </div>
            </div>
            <div class="tweet-comment-text">
              <%= simple_format(tweetcomment.text) %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>