config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'customers/show'

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }
  devise_scope :customer do
    get 'residences', to: 'customers/registrations#new_residence'
    post 'residences', to: 'customers/registrations#create_residence'
  end

  devise_for :shopkeepers, controllers: {
    registrations: 'shopkeepers/registrations',
    sessions: 'shopkeepers/sessions',
    passwords: 'shopkeepers/passwords'
  }
  devise_scope :shopkeeper do
    get 'addresses', to: 'shopkeepers/registrations#new_address'
    post 'addresses', to: 'shopkeepers/registrations#create_address'
  end

  resources :shops, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :items, only: [:show, :new, :create, :edit, :update ,:destroy] do
      collection do
        get 'search'
      end
      resources :itemcomments, only: :create
      resources :purchases, only: [:index, :create] do
        collection do
          get 'done'
        end
      end
    end
    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resources :tweetcomments, only: :create
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :customers, only: :show
  resources :residences, only: [:show, :update]
  resources :shopkeepers, only: :show
  resources :address, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :favorites, only: :index

  root to: "shops#index"

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :item_set
  before_action :shop_set

  def done
  end

  def index
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    card = Card.find_by(customer_id: current_customer.id)

    redirect_to new_card_path and return unless card.present?

    customer = Payjp::Customer.retrieve(card.customer_token)
    @card = customer.cards.first
  end

  def create
    if current_customer.card.present?
      
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer_token = current_customer.card.customer_token
      Payjp::Charge.create(
        amount: @item.price,
        customer: customer_token,
        currency: 'jpy'
      )

      Purchase.create(item_id: params[:item_id], customer_id: current_customer.id)

      @item.decrement(:stock, 1)
      @item.save
      
      redirect_to done_shop_item_purchases_path
    else 
      redirect_to new_card_path
    end
  end

  private

  def item_set
    @item = Item.find(params[:item_id])
  end

  def shop_set
    @shop = Shop.find(params[:shop_id])
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/done.html.erb
<%= render 'shared/header' %>

<div class="purchase-success">
  <div>
  購入が完了しました！ありがとうございました！！
  </div>
  <div class="purchase-done-link">
    <%= link_to "トップへ戻る", root_path, class:"action-link"%>
  </div>
</div>

app/views/purchases/index.html.erb
<%= render 'shared/header' %>

<div class="purchase">
  <div class="purchase-top">
    <div class="item-show-shop-name">
      <%= link_to  @shop.name, shop_path(@shop.id), class:"item-show-shop-link"%>
    </div>
    <div class="item-show-image">
      <%= image_tag @item.image, class:"item-show-item-image" %>
    </div>
    <div class="item-show-item-detail">
      <div class="item-show-item-name">
        <%= @item.name %>
      </div>
      <div class="item-show-item-price">
        ￥<%= @item.price %>
      </div>
    </div>
  </div>
  <div class="purchase-bottom">
    <div class="purchase-customer-info">
      ご確認をお願いいたします。
      <h3>【お届け先】</h3>
      <div class="purchase-customer-address">
        <b>郵便番号</b>
      </div>
      <div class="customer-address">
        <%= current_customer.residence.postal_code %>
      </div>
      <div class="purchase-customer-address">
        <b>都道府県</b>
      </div>
      <div class="customer-address">
        <%= current_customer.residence.prefecture.name %>
      </div>
      <div class="purchase-customer-address">
        <b>市町村区</b>
      </div>
      <div class="customer-address">
        <%= current_customer.residence.house_num %>
      </div>
      <% if current_customer.residence.building_name.present? %>
        <div class="purchase-customer-address">
          <b>建物名</b>
        </div>
        <div class="customer-address">
          <%= current_customer.residence.building_name %>
        </div>
      <% end %>
      <h3>【カード情報】</h3>
      <div class="purchase-customer-address">
        <b>カード番号</b>
      </div>
      <div class="customer-address">
        <%= "**** **** ****" + @card[:last4] %>
      </div>
      <div class="purchase-customer-address">
        <b>有効期限</b>
      </div>
      <div class="customer-address">
        <%= @card[:exp_month] %>/<%= @card[:exp_year] %>
      </div>
      </div>

    <div class="purchase-info">

        <%= link_to "マイページで編集", customer_path(current_customer), class:"action-link" %>
        <%= link_to "購入", shop_item_purchases_path(@shop, @item), method: :create, class:"action-link" %>
    </div>
  </div>
</div>