config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'customers/show'

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }
  devise_scope :customer do
    get 'residences', to: 'customers/registrations#new_residence'
    post 'residences', to: 'customers/registrations#create_residence'
  end

  devise_for :shopkeepers, controllers: {
    registrations: 'shopkeepers/registrations',
    sessions: 'shopkeepers/sessions',
    passwords: 'shopkeepers/passwords'
  }
  devise_scope :shopkeeper do
    get 'addresses', to: 'shopkeepers/registrations#new_address'
    post 'addresses', to: 'shopkeepers/registrations#create_address'
  end

  resources :shops, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :items, only: [:show, :new, :create, :edit, :update ,:destroy] do
      collection do
        get 'search'
      end
      resources :itemcomments, only: :create
      resources :purchases, only: [:index, :create] do
        collection do
          get 'done'
        end
      end
    end
    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resources :tweetcomments, only: :create
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :customers, only: :show
  resources :residences, only: [:show, :update]
  resources :shopkeepers, only: :show
  resources :address, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :favorites, only: :index

  root to: "shops#index"

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<div class="wrapper">
  <div class="wrapper-inner">
  <div class="top-header">
    <h1><%= link_to "MyShop", root_path, class:"myshop" %></h1>
  </div>
  <div class="search-form">
  </div>
  <div class="user-header">
    <% if customer_signed_in? %>
      <i class="far fa-user-circle"></i><%= link_to "マイページへ", customer_path(current_customer), class:"header-user" %>
      <i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_shopkeeper_session_path, method: :delete, class:"header-user" %>
    <% elsif shopkeeper_signed_in? && current_shopkeeper.shop.nil? %>
      店舗の設定を行いましょう！
      <i class="fas fa-store-alt"></i><%= link_to '店舗の設定を行う', '/shops/new' %>
      <i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_shopkeeper_session_path, method: :delete, class:"header-user" %>
    <% elsif shopkeeper_signed_in? && current_shopkeeper.shop.present? %>
      <i class="fas fa-store"></i><%= link_to '店舗へ', shop_path(current_shopkeeper), class:"header-user" %>
      <i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_shopkeeper_session_path, method: :delete, class:"header-user" %>
    <% else %>
      
      <i class="fas fa-user-plus"></i><%= link_to "新規登録", new_customer_registration_path, class:"header-user" %>
      <i class="fas fa-store-alt"></i><%= link_to "新規出店の方はこちら", new_shopkeeper_registration_path, class:"header-user" %>
      <i class="fas fa-sign-in-alt"></i><%= link_to "ログイン", new_customer_session_path, class:"header-user" %>
      <i class="fas fa-store"></i><%= link_to "ログイン（店主）", new_shopkeeper_session_path, class:"header-user" %>
    <% end %>
  </div>
  </div>
</div>